name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            os: ubuntu-latest
          - name: mac
            os: macos-latest
          - name: windows
            os: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          autocrlf: false
      - name: Install dotfiles
        shell: bash
        run: .bin/install.sh

